stages:
  - build

.build:
  stage: build
  image: coqorg/${CI_JOB_NAME}
  tags:
    - au
  before_script:
    - if [ -n "${COMPILER_EDGE}" ]; then opam switch ${COMPILER_EDGE} && eval $(opam env); fi
    - opam update -y
    - opam config list
    - opam repo list
    - opam list
    - git clone --branch $COQ_CONTAINERS_BRANCH https://github.com/StekiKun/containers.git dep-coq-containers
    - cd dep-coq-containers
    - make -j
    - make -f Makefile.coq install
    - cd ..
    - rm -rf dep-coq-containers
  script:
    - sudo chown -R coq:coq "$CI_PROJECT_DIR"
    - make -j

coq:8.6:
  extends: .build
  variables:
    COQ_CONTAINERS_BRANCH: 'v8.6'

coq:8.7:
  extends: .build
  variables:
    COQ_CONTAINERS_BRANCH: 'v8.7'

coq:8.8:
  extends: .build
  variables:
    COQ_CONTAINERS_BRANCH: 'v8.8'

coq:8.9:
  extends: .build
  variables:
    COQ_CONTAINERS_BRANCH: 'various-fixes'

## coq:dev:
##   extends: .build
##   variables:
##     COQ_CONTAINERS_BRANCH: 'various-fixes'
