stages:
  - build

.build:
  stage: build
  image: coqorg/${CI_JOB_NAME}
  tags:
    - au
  before_script:
    - if [ -n "${COMPILER_EDGE}" ]; then opam switch ${COMPILER_EDGE} && eval $(opam env); fi
    - opam repo add iris-dev https://gitlab.mpi-sws.org/iris/opam.git
    - opam update -y
    - opam config list
    - opam repo list
    - opam list
    - opam install coq-stdpp
  script:
    - sudo chown -R coq:coq "$CI_PROJECT_DIR"
    - make -j
    - coqwc theories/*.v

coq:8.8:
  extends: .build

coq:8.9:
  extends: .build

coq:8.10:
  extends: .build

coq:dev:
  extends: .build
