job:
  tags:
    - au

stages:
  - build

.build:
  stage: build
  image: coqorg/${CI_JOB_NAME}
  before_script:
    - if [ -n "${COMPILER_EDGE}" ]; then opam switch ${COMPILER_EDGE} && eval $(opam env); fi
    - opam update -y
    - opam config list
    - opam repo list
    - opam list
  script:
    - sudo chown -R coq:coq "$CI_PROJECT_DIR"
    - make

coq:8.4:
  extends: .build

coq:8.5:
  extends: .build

coq:8.6:
  extends: .build

coq:8.7:
  extends: .build

coq:8.8:
  extends: .build

coq:8.9:
  extends: .build

coq:dev:
  extends: .build
